version: "3.7"

services:
  idp:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    platform: linux/amd64
    command: ["start-dev"]
    ports:
      - 19990:9990 # 管理者コンソール
      - 18080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
