version: "3.7"

volumes:
  node_modules_volume:

services:
  idp:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    platform: linux/amd64
    command: ["start-dev"]
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
  webapp:
    container_name: webapp
    image: node
    command: ["npm", "run", "dev"]
    volumes:
      - ./my-app:/project/my-app
      - node_modules_volume:/project/my-app/node_modules
    working_dir: /project/my-app
    ports:
      - 13000:3000
